### ISSUE TITLE
Thaumcraft arcane workbench receipes added to worktable

### ISSUE THREAD

**Issue by 1mphuls3** [codetaylor/pyrotech-1.12#365] opened 2021-08-09 01:32 UTC
Issue Description

Crafting recipes for the Thaumcraft arcane workbench are added to the worktable. This is an issue because Thaumcraft requires vis crystals for crafting, and there are steps required to get the arcane workbench.

What You Expect to Happen

Arcane workbench recipes not to be added to the worktable

Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* CraftTweaker:
* Dropt: 1.18.0
* Pyrotech: 1.5.13
* Athenaeum: 1.19.2

**Comment by codetaylor** [comment] 2021-08-09 04:47
Duplicate of #80

**Closed by codetaylor** 2021-08-09 04:47 UTC
