### ISSUE TITLE
Need help with custom ores (crash)

### ISSUE THREAD

**Issue by CactusDuud** [codetaylor/pyrotech-1.12#306] opened 2020-06-13 02:52 UTC
#### What Happens

Trying to define custom ores, but I keep getting a crash I don't really understand.

#### What You Expect to Happen

Proper load

#### Script

In this case it's the [config](https://pastebin.com/n88JbVAb)

#### Crash Log

[Log](https://pastebin.com/CxkgWPBa)

#### Affected Versions

* Minecraft: 1.12
* Forge: forge-14.23.5.2854
* CraftTweaker: n/a
* Dropt: 1.18.0
* Pyrotech: 1.4.29
* Athenaeum: 1.18.1

**Comment by codetaylor** [comment] 2020-06-13 16:16
Thanks for the report!

I took a quick look at the code and it doesn't seem to like lang entries that don't have a `:` in them or lang entries that aren't found in a lang file. The docs say it should work without the `:` and I'm pretty sure that it was intended to work with non-key strings like you're using. I'll look at it longer when I have some time.

**Comment by CactusDuud** [comment] 2020-06-13 20:48
Update: It successfully ran when I removed the lang entries you mentioned.

**Comment by codetaylor** [comment] 2020-06-29 21:44
This wasn't intended to work with non-key strings, but it was supposed to work with valid lang keys without a `:` separator. This will be fixed in `1.5.0`.

**Closed** 2020-07-12 18:21 UTC
Labels: bug, complete
