### ISSUE TITLE
Different fluid capability on blocks?

### ISSUE THREAD

**Issue by Primitive-Human** [codetaylor/pyrotech-1.12#420] opened 2023-04-11 19:33 UTC
#### Intro
I like to integrate Pyrotech's blocks into my multiblocks using MultiBlocked where I can use these as inputs and outputs for my more primitive machines. Except I've come across a problem regarding (fluid) capabilities.

#### Issue Description

The several placed fluid containers in Pyrotech seem to have a different implementation of the fluid capability, which leads to other mods not recognizing these blocks as proper fluid containers. And this is a problem when another mod only accepts blocks through the capability system, like MultiBlocked. 

#### What Happens

Using the Screen with Fluid Screen module from RFTools, I try to detect the amount of fluid in Pyrotech placed fluid containers (Barrel, stone/refractory tank, collectors, soaking pot etc), and found that most of these do not properly register as a fluid container. I make this statement based on the RFTools Fluid Screen module being able to recognize, or not recognize a proper fluid container, as well as the fluid bar in The One Probe showing up.

I've added the following screenshots to explain further what I mean.

Screenshot 1: 
On the floor I have placed all placeable fluid containers that Pyrotech offers. Behind them on the wall, I have creative RFTools screens with fluid modules, each individually linked to a Pyrotech fluid container. The top row is for the blocks in the back row, while the bottom row is for the blocks in the front row.

![2023-04-11_21 19 33](https://user-images.githubusercontent.com/81650773/231269242-17aadf6f-1a0e-403a-97d4-3dab0e02cfeb.png)

https://i.imgur.com/FHxbr2d.png

Moreover, on the left side of my screenshot, you can see the One Probe fluid bar overlay, showing the contents of the soaking pot, as well as the fluid content being showed on its dedicated fluid screen behind it.

Screenshot 2:
Compared to the soaking pot, another fluid container like the barrel, does not have the proper TOP fluid bar; instead it shows this separate info bar regarding the fluid contents.

![2023-04-11_21 19 42](https://user-images.githubusercontent.com/81650773/231269299-adf002eb-0a25-43c6-9778-d2a459f142bd.png)

https://i.imgur.com/fry86wf.png

And the dedicated RFTools fluid screen for the barrel does not show the contents of the barrel at all, despite it also having 1000 mB of water like every other block shown here.

In both screenshots, you can see which Pyrotech do have a properly implemented fluid capability system, and which ones did not. 

#### What You Expect to Happen

That all placed fluid containers register properly with the fluid capability system. So that I can utilize these blocks in my own custom multiblocks that utilizes inputs and outputs based on the Forge capability system. 

#### Script

No scripts used

#### Crash Log

No errors or crashes or other abnormalities were observed in the log.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* CraftTweaker: Not used
* Dropt: 1.12.2-1.19.3
* Pyrotech: 1.12.2-1.6.7 (not 1.6.8 as I don't update for localization updates)
* Athenaeum: 1.12.2-1.19.5

**Comment by codetaylor** [comment] 2023-04-12 17:57
Pyrotech fluid blocks use the default fluid capability provided by Forge, just like most everything.

The Pyrotech fluid blocks use different sides for their fluid access and some are only exposed via the configs. For example, IIRC, the barrel uses the top as it's fluid side. Maybe this interferes with how RFTools accesses the capability, I don't know their code. It would need to access the capability passing the correct side and not `null` for the side.

**Comment by codetaylor** [comment] 2023-04-12 18:02
> Compared to the soaking pot, another fluid container like the barrel, does not have the proper TOP fluid bar; instead it shows this separate info bar regarding the fluid contents.

Correct. This is because of a custom ToP provider. It has nothing to do with the underlying fluid capability.
https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/tech/basic/plugin/top/provider/BarrelProvider.java#L73

The barrel requires the automation flag to be set in the config for the fluid capabilities to be exposed: https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/tech/basic/tile/TileBarrel.java#L317

**Comment by codetaylor** [comment] 2023-10-12 22:16
So, compatibility with the Hot or Not+ mod doesn't have anything to do with the NBT data on the tank.

Hot or Not [looks for a fluid capability](https://github.com/ACGaming/HotOrNotPlus/blob/hotornot-1.12.x/src/main/java/com/buuz135/hotornot/server/ServerTick.java#L44) on the item which the [Embers Vessel has](https://github.com/DaedalusGame/EmbersRekindled/blob/rekindled/src/main/java/teamroots/embers/item/block/ItemBlockTank.java#L30) and the [Pyrotech buckets have](https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/bucket/item/ItemBucketBase.java#L797).

The Pyrotech tank items do not have a fluid capability.

Today I've added a tank item as well as a fluid capability on that item. This should solve the mod compatibility issue, but I haven't tested it.

As a result of adding the fluid capability, I did clean up the item-serialized NBT to make it easier to implement the fluid capability. Here's what the NBT looks like now:

![image](https://github.com/codetaylor/pyrotech-1.12/assets/1240716/d145a019-e97f-4be6-b2ea-b861e6efbe1b)

I also found and fixed an issue with multiblock tank fluid settling.

@Primitive-Human If you could please test this interim build for compatibility with Hot or Not+ I would appreciate it. Thank you.

[pyrotech-1.12.2-1.6.8-3-g6d20103f.zip](https://github.com/codetaylor/pyrotech-1.12/files/12887468/pyrotech-1.12.2-1.6.8-3-g6d20103f.zip)

**Comment by codetaylor** [comment] 2023-10-13 15:24
> In my quick tests, the refractory tank, and the stone tank after enabling hot fluids, work with HotorNot+ as expected.

Great!

> They also function as buckets now which is great.

They should only function as buckets inside of machines that accept buckets in slots. They should not be able to collect fluids from the world.

> The ability to stack tanks got broken however. Empty tanks taken from JEI which have no NBT tag do not connect to each other. All of their "connection" blockstate defaults to "none", regardless of their position in a stack.

You're not wrong. I tested this yesterday and it worked fine. I'm looking at it now.

Yep, I was testing with pre-existing tanks which had NBT. Testing tanks without NBT revealed a flaw in the logic. Fixed.

> And the issue with multiblock tank fluid settling doesn't seem to be fixed by this; the simple multiblock in the screenshot takes water and produces iron ingots with it in the chest; but no matter which input side I select for the stone tank, fluid isn't used and the machine doesn't run.

Ok, so fluid settling doesn't have anything to do with the tank's interaction with that mod. Fluid settling refers to fluids from a top tank flowing down and settling into bottom tanks.

I don't know why the tank doesn't interact properly with that mod.

The tanks provide a [fluid capability for all sides](https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/storage/tile/spi/TileTankBase.java#L360).

---

Fixed stacking: 
[pyrotech-1.12.2-1.6.8-4-g1bd3dd8d.zip](https://github.com/codetaylor/pyrotech-1.12/files/12895080/pyrotech-1.12.2-1.6.8-4-g1bd3dd8d.zip)

**Comment by codetaylor** [comment] 2023-10-13 15:57
> ... but no matter which input side I select for the stone tank, fluid isn't used and the machine doesn't run.

It's possible that the compatibility issue is caused by the tank's fluid capability returning an empty `IFluidTankProperties` array, as [you can see here](https://github.com/codetaylor/pyrotech-1.12/blob/master/src/main/java/com/codetaylor/mc/pyrotech/modules/storage/tile/spi/TileTankBase.java#L379).

If the mod is interrogating the properties of the fluid capability for retrieval, then it would likely not work.

I've implemented the tank properties properly in the build below.

@Primitive-Human Please test this build with your multiblock. If this doesn't solve the problem, let me know what mod that is.

---

Proper implementation of `public IFluidTankProperties[] getTankProperties()` in tank fluid capability:
[pyrotech-1.12.2-1.6.8-6-g57d14300.zip](https://github.com/codetaylor/pyrotech-1.12/files/12895394/pyrotech-1.12.2-1.6.8-6-g57d14300.zip)

**Comment by codetaylor** [comment] 2023-10-13 21:35
> While I do receive some errors whenever creating this multiblock, I don't believe this is on your part but MBD.

No, that looks like my end.

**Comment by codetaylor** [comment] 2023-10-13 22:17
New interim build:
- Fix index exception when client queries tank properties before tank group is set
- Fix class cast exception in tank group algorithm
- Fix tanks with fluid should connect to empty tanks above

---

[pyrotech-1.12.2-1.6.8-10-g0128add1.zip](https://github.com/codetaylor/pyrotech-1.12/files/12899806/pyrotech-1.12.2-1.6.8-10-g0128add1.zip)

**Comment by codetaylor** [comment] 2023-10-14 02:10
Great! I'll push an update in the next day or two.

**Comment by codetaylor** [comment] 2023-10-14 15:35
Fixed in `1.12.2-1.6.9`

**Closed by codetaylor** 2023-10-14 15:35 UTC
Labels: bug, reproduced, complete
